-- Partie 1

-- Ajout des clés primaires

ALTER TABLE FOURNISSEUR ADD
CONSTRAINT pk_fournisseur
PRIMARY KEY (NOMFOUR);

ALTER TABLE PRODUIT ADD
CONSTRAINT pk_produit
PRIMARY KEY (NOMFOUR, APPELLATION);

ALTER TABLE COMMANDE ADD
CONSTRAINT pk_commande
PRIMARY KEY (NOCOM);
